# Generated by Django 4.2.18 on 2025-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
