# Generated by Django 4.2.18 on 2025-01-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='featured_image',
        ),
    ]
