# Generated by Django 4.2.18 on 2025-01-29 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
