# Generated by Django 4.2.18 on 2025-01-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutimage',
            old_name='image',
            new_name='featured_image',
        ),
    ]
